### ISSUE TITLE
Package Manager failed to resolve issues

### ISSUE THREAD

**Issue by PublicVoidUpdate** [ashblue/fluid-dialogue#27]
I am running Beta Unity 2022 using Core 2D, I receive this issue upon opening the altered unity project, (attached below because I can't copy and paste the text directly D:) 
![image](https://user-images.githubusercontent.com/81382069/160661112-db9a912b-cd39-4fee-9560-1c7334543c80.png)
[](url)
my manifest.json file reads as follows "
{
  "scopedRegistries": [
    {
      "name": "NPM",
      "url": "https://registry.npmjs.org",
      "scopes": [
        "clever-crow",
        "com.fluid"
      ]
    }
  ],
  "dependencies": {
    "clever-crow.nsubstitute": "2.0.3",
    "com.fluid.database": "2.0.0",
    "com.fluid.find-and-replace": "1.0.1",
    "com.fluid.simple-spellcheck": "1.1.0",
    "com.fluid.unity-event-plus": "1.1.0",
	  "com.fluid.dialogue": "1.0.0"
    "com.unity.collab-proxy": "1.15.13",
    "com.unity.feature.2d": "1.0.0",
    "com.unity.ide.rider": "3.0.12",
    "com.unity.ide.visualstudio": "2.0.14",
    "com.unity.ide.vscode": "1.2.5",
    "com.unity.test-framework": "1.1.31",
    "com.unity.textmeshpro": "3.0.6",
    "com.unity.timeline": "1.7.0-pre.2",
    "com.unity.ugui": "1.0.0",
    "com.unity.visualscripting": "1.7.5",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.androidjni": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  }
}
" any help would be greatly appreciated!

**Comment by PublicVoidUpdate** [comment]
I should say i am trying to follow the install instructions and this is my first time altering the manifest.json, sorry if this is a stupid mistake.

**Comment by ashblue** [comment]
@PublicVoidUpdate sorry I'm just getting to this now. What you have there looks fine to me. That error is definitely a typo in the JSON somewhere. I'd try an online json validator to find the issue like this https://jsonlint.com/. For these sorta questions the Discord is a great place to ask for help. Closing for now but feel free to open a message once you join the community below.

https://discord.com/invite/8QHFfzn
